### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by ZeroThe2nd** [eldomagan/vuex-orm-localforage#1]
It's unclear from the readme what the `database` import should be. Does this need to be a localforage instance, localforage itself, or what is it exactly supposed to be?

**Comment by eldomagan** [comment]
Hi @ZeroThe2nd, thank you for your interest for this library.
It still a work in progress in progress. I will update the readme to be more comprehensible.

`database` is the VuexORM database instance 
```js
const database = new VuexORM.Database()
```
See https://vuex-orm.github.io/vuex-orm/guide/prologue/getting-started.html#create-modules for more infos.

**Comment by ZeroThe2nd** [comment]
Ah, got it. Thanks for the quick response 😄

**Comment by eldomagan** [comment]
I updated the readme with some usage sample.

**Comment by ZeroThe2nd** [comment]
Sweet! Thanks a bunch
