### ISSUE TITLE
$delete (or remapped $deleteFromLocal) cause "Uncaught (in promise) TypeError: Cannot read property '$id' of null"

### ISSUE THREAD

**Issue by DQvsRA** [eldomagan/vuex-orm-localforage#10]
I'm in situation when I want to refresh local storage and load config again everytime to check how some properties of the model generated in `afterCreate`. Doing this:
```
await ConfigModel.$fetchFromLocal()
if (ConfigModel.exists()) await ConfigModel.$deleteFromLocal()
```
cause the error:
```
Action.js?e7b0:23 Uncaught (in promise) TypeError: Cannot read property '$id' of null
    at Function.getRecordKey (Action.js?e7b0:23)
    at eval (Destroy.js?ce07:17)
    at Array.map (<anonymous>)
    at eval (Destroy.js?ce07:16)
```

**Comment by eldomagan** [comment]
The `$delete` (`$deleteFromLocal`) action work like the vuex-orm `delete` action which need the record id ([https://vuex-orm.github.io/vuex-orm/guide/data/deleting.html](https://vuex-orm.github.io/vuex-orm/guide/data/deleting.html)).

If you have multiple records of the ConfigModel, you need to use `deleteAll` action which is not implemented here. Would add support for that asap.
