### ISSUE TITLE
[Dependencies] How to remove lodash-es from final build

### ISSUE THREAD

**Issue by DQvsRA** [eldomagan/vuex-orm-localforage#12]
Library lodash-es take too much weight in the build. How could I remove or may be owners of the lib can?

![image](https://user-images.githubusercontent.com/442111/78239415-f5e15080-74dd-11ea-9af5-1bee3a681218.png)

Duplicated from: https://github.com/vuejs/vue-cli/issues/5262

**Comment by eldomagan** [comment]
I just released a new version (lodash free). Sorry it took so long, I hope it's not too late for you.

**Comment by DQvsRA** [comment]
Just want to say - thank you for your effort!
