### ISSUE TITLE
how to include vuex-orm-localforage into vuex-orm-examples?

### ISSUE THREAD

**Issue by jfqd** [eldomagan/vuex-orm-localforage#7]
I am wondering how to include `vuex-orm-localforage` into the [vuex-orm-examples](https://github.com/vuex-orm/vuex-orm-examples) demo app.

I tried to include the following code from the readme

```
import VuexORMLocalForage from 'vuex-orm-localforage'

const database = new VuexORM.Database()

VuexORM.use(VuexORMLocalForage, {
  database
})
```

into [src/store/index.js](https://github.com/jfqd/vuex-orm-examples/blob/master/src/store/index.js) so it now looks like:

```
import Vue from 'vue'
import Vuex from 'vuex'
import VuexORM from '@vuex-orm/core'
import VuexORMLocalForage from 'vuex-orm-localforage'
import database from '@/database'

Vue.use(Vuex)

VuexORM.use(VuexORMLocalForage, {
  database
})

const store = new Vuex.Store({
  namespaced: true,
  plugins: [VuexORM.install(database)]
})

export default store
```

But I am not able to enter any user name nor todo. Maybe this approach was to naiv, but how can it be accomplished?

**Comment by eldomagan** [comment]
Hi @jfqd. I have setup a repository with a working example [https://github.com/eldomagan/vuex-orm-localforage-exemples](https://github.com/eldomagan/vuex-orm-localforage-exemples). Check it out.

The issue was that actions introduced by vuex-orm-localforage ($create, $update,...) are not available as instance method on models.

**Comment by jfqd** [comment]
@eldomagan Thanks a lot for your help which is totally awesome!

**Comment by jfqd** [comment]
OT: @eldomagan Is there a donation-button for your project?

**Comment by eldomagan** [comment]
No, I didn't setup one. Thanks.
