### ISSUE TITLE
vuex-orm-localforage breaks with @vuex-orm/core 0.34.1

### ISSUE THREAD

**Issue by surfgreendev** [eldomagan/vuex-orm-localforage#9]
Hi there! 

I tried to implement your awesome package into my vue.js project. 
The current version of your package breaks with @vuex-orm/core 0.34.1, so that vuex orm still working but data is not inserted into IndexedDB.

The error message that is emitted as follows:

`Model.js?0f48:12 Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at Function.isFieldAttribute (Model.js?0f48:12)
    at eval (Model.js?0f48:22)
    at Array.filter (<anonymous>)
    at Function.getPersistableFields (Model.js?0f48:22)
    at eval (Persist.js?3fa2:32)
    at Array.map (<anonymous>)
    at eval (Persist.js?3fa2:29)`

package.json

`{
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-eslint": "^3.12.1",
    "@vue/cli-service": "^3.12.1",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vuex-orm/core": "^0.34.1",
    "normalize.css": "^8.0.1",
    "postcss-css-variables": "^0.13.0",
    "postcss-import": "^12.0.1",
    "postcss-nested": "^4.2.1",
    "vue": "^2.6.10",
    "vue-template-compiler": "^2.6.10",
    "vuex": "^3.1.2"
  },
  "dependencies": {
    "vuex-orm": "^0.15.0",
    "vuex-orm-localforage": "^0.2.3"
  }
}`

I've tested it with your example project.

Could you please fix it?

Best,

Carl

**Comment by eldomagan** [comment]
Hi @surfgreendev, thanks for reporting this. I will check this as soon as possible.

**Comment by eldomagan** [comment]
Hi @surfgreendev, i just fixed it and publish new version 0.2.4. Please check it out.

**Comment by surfgreendev** [comment]
Hi @eldomagan, thanks for the fast support. Will check it out today and let you know.

Do you have a donor button or sth like that?

Best,

Carl

**Comment by surfgreendev** [comment]
Hi @eldomagan,

works great! Thx a lot. 

Best,

Carl
